documentation: add rpcgen tool to required packages
On recent distros the following error appears without rpcgen host tool:
  ERROR: The following required tools (as specified by HOSTTOOLS)
  appear to be unavailable in PATH, please install them in order to
  proceed:
    rpcgen

Signed-off-by: Goran Cengic <cengic@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>